
export const SocialProofSection = () => {
  const testimonials = [
    {
      quote: "Recap helped me prove my value during performance reviews — no more guessing what I did last month!",
      author: "Adebayo O.",
      role: "Frontend Developer",
      avatar: "AO"
    },
    {
      quote: "Honestly, this makes standups a breeze. I just show the AI summary!",
      author: "Jane L.",
      role: "Product Designer",
      avatar: "JL"
    },
    {
      quote: "My career portfolio went from zero to impressive in weeks. Recap tracked everything I forgot.",
      author: "Marcus R.",
      role: "Data Scientist",
      avatar: "MR"
    }
  ];

  return (
    <section className="py-16 bg-white">
      <div className="container mx-auto px-4">
        <div className="text-center mb-16">
          <h2 className="text-3xl lg:text-4xl font-bold text-gray-900 mb-4">
            Loved by professionals everywhere
          </h2>
        </div>

        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8 max-w-6xl mx-auto mb-12">
          {testimonials.map((testimonial, index) => (
            <div 
              key={index}
              className="bg-gray-50 rounded-xl p-6 shadow-md hover:shadow-lg transition-shadow duration-300"
            >
              <div className="mb-4">
                <div className="flex text-yellow-400 mb-3">
                  {[...Array(5)].map((_, i) => (
                    <Star key={i} className="w-4 h-4 fill-current" />
                  ))}
                </div>
                <p className="text-gray-700 italic leading-relaxed">
                  "{testimonial.quote}"
                </p>
              </div>
              <div className="flex items-center space-x-3">
                <div className="w-10 h-10 bg-blue-600 rounded-full flex items-center justify-center text-white font-semibold">
                  {testimonial.avatar}
                </div>
                <div>
                  <div className="font-semibold text-gray-900">{testimonial.author}</div>
                  <div className="text-sm text-gray-600">{testimonial.role}</div>
                </div>
              </div>
            </div>
          ))}
        </div>

        {/* Example Recap Preview */}
        <div className="max-w-2xl mx-auto bg-blue-50 rounded-xl p-8">
          <h3 className="text-lg font-semibold text-blue-900 mb-4">
            Example Recap – Generated from 3 tasks + 1 note
          </h3>
          <div className="bg-white rounded-lg p-6 shadow-sm">
            <div className="text-sm text-gray-600 mb-2">Daily Summary for March 15, 2024</div>
            <p className="text-gray-800 leading-relaxed">
              Today I focused on three key areas: completed the user authentication flow for our mobile app, 
              reviewed and provided feedback on the new design system components, and resolved two critical 
              bugs in the payment processing module. I also documented my learnings about React performance 
              optimization techniques, which will be valuable for our upcoming code review sessions.
            </p>
            <div className="mt-4 text-xs text-blue-600">
              ✨ Generated by Recap AI
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};
